### ISSUE TITLE
Run asyncio loop in main thread

### ISSUE THREAD

**Issue by maxfischer2781** [MaineKuehn/cobald#8]
The ``asyncio`` subprocessing (possibly other features) requires an event loop in the main thread. See https://github.com/qtile/qtile/issues/1046#issuecomment-379314184 and [asyncio/subprocess-and-threads](https://docs.python.org/3/library/asyncio-subprocess.html#subprocess-and-threads).

**Comment by maxfischer2781** [comment]
This requires making the ``asyncio`` runner the one to spawn and handle all others. Runners must therefore use ``async def run`` instead of ``def run``.

**Comment by maxfischer2781** [comment]
Does this fix the problem in your case, @giffels?

**Comment by giffels** [comment]
@maxfischer2781: Thanks a lot. It fixes the problem.

Cheers,
Manuel
